### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tarik02** [pygy/ffi-enum.lua#1]

**Comment by pygy** [comment]
MIT (See the [end of the source file](https://github.com/pygy/ffi-enum.lua/blob/990cd3392383920a7b0a9859d96f3f15d0eaf56b/ffi-enum.lua#L194))... edit... and the second line of the README...

**Comment by tarik02** [comment]
Sorry... what about adding LICENSE file?

**Comment by pygy** [comment]
Feel free to file a PR :-)
